name: observability-datadog
services:
  datadog-agent:
    container_name: datadog-agent
    image: gcr.io/datadoghq/agent:7
    restart: unless-stopped
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE}
      - DD_ENV=develop
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_CONTAINER_EXCLUDE_LOGS="name:agent"
      - DD_LOGS_DIRECT_SUBMISSION_INTEGRATIONS=Serilog
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      #- /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - observability-datadog-network
    ports:
      - "8126:8126/tcp"
      - "8125:8125/udp"
  
  sample-api:
    container_name: sample-api
    image: sample-api:latest
    build:
      context: ./SampleApi/
      dockerfile: Dockerfile
      args:
        version: latest
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DD_AGENT_HOST=datadog-agent
      - DD_ENV=develop
      - DD_SERVICE=sample-api
      - DD_VERSION=1.0.0
      - DD_TRACE_ENABLED=true
      - DD_LOGS_INJECTION=true
      - DD_LOGS_ENABLED=true
      - DD_LOG_LEVEL=INFO
      - CORECLR_ENABLE_PROFILING=1
      - CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
      - CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
      - DD_DOTNET_TRACER_HOME=/opt/datadog
      - DD_LOGS_DIRECT_SUBMISSION_INTEGRATIONS=Serilog
    ports:
      - "5500:80"
    networks:
      - observability-datadog-network
    depends_on:
      - datadog-agent
networks:
  observability-datadog-network:
    driver: bridge